config/routes.rb
Rbtrack::Application.routes.draw do
  root to: 'static_pages#home'
  resources :users
  resources :projects, only: [:new, :create, :show, :index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :issues, except: :index
  resources :comments, only: [:create]
  match '/assign', to: 'issues#assign', via: :put
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/invite', to: 'TeamMemberships#invite', via: :post
  match '/accept_invitation', to: 'TeamMemberships#accept_invitation', via: :put
  match '/reject_invitation', to: 'TeamMemberships#reject_invitation', via: :put
  match '/search', to: 'search#search'

end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id          :integer         not null, primary key
#  project_id  :integer
#  user_id     :integer
#  assignee_id :integer
#  subject     :string(255)
#  description :text
#  status      :integer
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#  priority    :integer
#

class Status
  ACTIVE = 0
  TO_BE_FIXED = 1
  CLOSED = 2
  FIXED = 3
  DUPLICATE = 4
  WONT_FIX = 5
  BY_DESIGN = 6
  def self.to_string(status)
    case status
      when ACTIVE then 'Active'
      when TO_BE_FIXED then 'To be fixed'
      when CLOSED then 'Closed'
      when FIXED then 'Fixed'
      when DUPLICATE then 'Duplicate'
      when WONT_FIX then 'Won\'t fix'
      when BY_DESIGN then 'By design'
      else raise ArgumentError
    end
  end
end

class Priority
  LOWEST = 0
  LOW = 1
  NORMAL = 2
  HIGH = 3
  HIGHER = 4
  CRITICAL = 5
  def self.to_string(priority)
    case priority
      when LOWEST then 'Lowest'
      when LOW then 'Low'
      when NORMAL then 'Normal'
      when HIGH then 'High'
      when HIGHER then 'Higher'
      when CRITICAL then 'Critical'
      else raise ArgumentError
    end
  end
  def self.all
    [LOWEST, LOW, NORMAL, HIGH, HIGHER, CRITICAL]
  end
end

class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :assignee, class_name: 'User'
  has_many :comments
  default_scope order: 'issues.priority DESC, issues.created_at DESC'

  attr_accessible :description, :status, :subject, :project_id

  validates :subject, presence: true, length: { minimum: 8, maximum: 100 }
  validates :project_id, presence: true
  validates :user_id, presence: true

  before_create -> issue do
    issue.status = Status::ACTIVE
    issue.priority = Priority::NORMAL
  end

  def closed?
    status != Status::ACTIVE && status != Status::TO_BE_FIXED
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :signed_in_user, except: :show
  before_filter :correct_user, only: [:edit, :update]
  before_filter :correct_assign, only: :assign
  before_filter :admin_user, only: :destroy

  def new
    @issue = Issue.new
    @selected_project = ''
    project_id = params[:project]
    if project_id
      project = Project.find_by_id(project_id)
      if project
        @selected_project = project.name
      end
    end
  end
  def create
    issue_info = get_issue_info()
    @issue = Issue.new(issue_info)
    @issue.user = current_user
    if @issue.save
      redirect_to @issue
    else
      render :new
    end
  end
  def show
    @issue = Issue.find(params[:id])
    @comment = current_user.comments.build if signed_in?
  end
  def edit
  end
  def update
    if params[:set_status]
      set_issue_status(params[:set_status])
      redirect_to @issue
    elsif params[:set_priority]
      set_issue_priority params[:set_priority]
      redirect_to @issue
    elsif @issue.update_attributes(params[:issue])
      flash[:success] = 'Issue was successfully updated.'
      redirect_to @issue
    else
      render :edit
    end
  end
  def assign
    @issue.assignee = @user
    @issue.save!
    flash[:success] = "Assigned issue ##{params[:id]} to #{@user ? @user.name : 'nobody'}"
    redirect_to @issue
  end
  def destroy
    issue = Issue.find(params[:id])
    issue.destroy
    flash[:success] = "Issue ##{issue.id}: #{issue.subject} have been removed."
    redirect_to issue.project
  end

private
  def set_issue_status(status_str)
    status = status_str.to_i
    @issue.status = status
    @issue.save!
    action = 'closed'
    action = 'reopened' if status == Status::ACTIVE
    action = 'confirmed' if status == Status::TO_BE_FIXED
    flash[:success] = "Issue was #{action}."
  end
  def set_issue_priority(priority_str)
    priority = priority_str.to_i
    @issue.priority = priority
    @issue.save!
    flash[:success] = 'Issue priority was updated.'
  end
  def get_issue_info
    issue_info = params[:issue]
    project = Project.find_by_name(issue_info[:project])
    issue_info[:project_id] = project.nil? ? -1 : project.id
    issue_info.delete(:project)
    issue_info
  end
  def correct_user
    @issue = Issue.find(params[:id])
    if params[:set_priority]
      redirect_to(root_path) unless @issue.project.users.include?(current_user)
    end
    if params[:set_status]
      status = params[:set_status].to_i
      if status == Status::CLOSED
        redirect_to(root_path) unless current_user?(@issue.user)
      elsif status != Status::ACTIVE
        redirect_to(root_path) unless @issue.project.users.include?(current_user)
      end
    end
    redirect_to(root_path) unless current_user?(@issue.user) || @issue.project.users.include?(current_user) || current_user.admin?
  end
  def correct_assign
    @issue = Issue.find(params[:id])
    @user = User.find_by_id(params[:user_id])
    redirect_to(root_path) unless @user.nil? || @issue.project.users.include?(@user)
    redirect_to(root_path) unless @issue.project.users.include?(current_user)
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  DEFAULT_CLASS = 'label'
  BLUE_CLASS = DEFAULT_CLASS + ' label-info'
  GREEN_CLASS = DEFAULT_CLASS + ' label-success'
  ORANGE_CLASS = DEFAULT_CLASS + ' label-warning'
  RED_CLASS = DEFAULT_CLASS + ' label-important'
  
  def css_id_from(str, postfix=nil)
    id = str.gsub(' ', '-').downcase
    "#{id}-#{postfix}" unless postfix.nil?
    id
  end
  def issues_id_from(str)
    css_id_from str, 'issues'
  end
  def white_icon(str)
    str + ' icon-white'
  end
  def icon_status_class_from(status)
    white_icon case status
      when Status::ACTIVE then 'icon-question-sign'
      when Status::TO_BE_FIXED then 'icon-screenshot'
      when Status::CLOSED then 'icon-minus-sign'
      when Status::FIXED then 'icon-ok'
      when Status::DUPLICATE then 'icon-tags'
      when Status::WONT_FIX then 'icon-ban-circle'
      when Status::BY_DESIGN then 'icon-ok-sign'
      else raise ArgumentError
    end
  end
  def label_status_class_from(status)
    case status
      when Status::ACTIVE then DEFAULT_CLASS
      when Status::TO_BE_FIXED then BLUE_CLASS
      when Status::CLOSED then RED_CLASS
      when Status::FIXED then GREEN_CLASS
      when Status::DUPLICATE then BLUE_CLASS
      when Status::WONT_FIX then RED_CLASS
      when Status::BY_DESIGN then ORANGE_CLASS
      else raise ArgumentError
    end
  end
  def icon_priority_class_from(priority)
    white_icon case priority
      when Priority::LOWEST then 'icon-chevron-down'
      when Priority::LOW then 'icon-chevron-down'
      when Priority::NORMAL then 'icon-minus'
      when Priority::HIGH then 'icon-chevron-up'
      when Priority::HIGHER then 'icon-chevron-up'
      when Priority::CRITICAL then 'icon-fire'
      else raise ArgumentError
    end
  end
  def label_priority_class_from(priority)
    case priority
      when Priority::LOWEST then DEFAULT_CLASS
      when Priority::LOW then GREEN_CLASS
      when Priority::NORMAL then BLUE_CLASS
      when Priority::HIGH then ORANGE_CLASS
      when Priority::HIGHER then RED_CLASS
      when Priority::CRITICAL then RED_CLASS
      else raise ArgumentError
    end
  end
end

app/views/issues/edit.html.erb
<% provide(:title, "Edit issue ##{@issue.id}") %>
<div id="issue">
  <div class="row">
    <div class="span6">
      <span id="project">Project: <%= link_to @issue.project.name, @issue.project %></span>
    </div>
  </div>
  <div class="row">
    <div class="span6">
      <span id="user">User: <%= link_to @issue.user.name, @issue.user %></span>
    </div>
  </div>
  <div></div>
  <div class="row">
    <div class="span12">
      <%= form_for @issue do |form| %>
        <%= render 'shared/error_messages', object: form.object %>
        <%= form.label :subject %>
        <%= form.text_field :subject %>
        <%= form.label :description %>
        <%= form.text_area :description %>
        <%= form.submit 'Save changes', class: 'btn btn-large btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/issues/new.html.erb
<% provide(:title, 'New issue') %>
<h1>New issue</h1>
<%= form_for @issue do |form| %>
  <%= render 'shared/error_messages', object: form.object %>
  <%= form.label :project %>
  <%= form.select :project, Project.names, { selected: @selected_project } %>
  <%= form.label :subject %>
  <%= form.text_field :subject %>
  <%= form.label :description %>
  <%= form.text_area :description %>
  <%= form.submit 'Submit new issue', class: 'btn btn-large btn-primary' %>
<% end %>

app/views/issues/show.html.erb
<% provide(:title, "#{@issue.project.name} # #{@issue.subject}") %>
<h1><span id="id">#<%= @issue.id %></span> <%= @issue.subject %></h1>
<div id="issue">
  <div class="row">
    <div class="span6">
      <div id="project">Project: <%= link_to @issue.project.name, @issue.project %></div>
      <div id="user">User: <%= link_to @issue.user.name, @issue.user %></div>
      <div>Assignee: <%= @issue.assignee ? (link_to @issue.assignee.name, @issue.assignee) : 'nobody' %>
        <% if @issue.project.users.include? current_user %>
          <%= link_to 'Assign ...', '#assign-issue-modal', class: 'btn btn-mini', 'data-toggle' => 'modal' %>
          <%= link_to 'to me', assign_path(id: @issue.id, user_id: current_user.id), method: :put, class: 'btn btn-mini' %>
        <% end %>
      </div>
      <div>Status: <%= render 'shared/issue_status_badge', status: @issue.status, tooltip: false %> <%= Status.to_string @issue.status %></div>
      <div>Priority: <%= render 'shared/issue_priority_badge', priority: @issue.priority, tooltip: false %> <%= Priority.to_string @issue.priority %></div>
      <% if @issue.project.users.include?(current_user) %>
        <!-- TODO: fix layout here -->
        <div class="btn-group">
          <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
            Change
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% Priority.all.each do |priority| %>
              <li><%= link_to Priority.to_string(priority),
                              priority == @issue.priority ? '#' : issue_path(@issue, set_priority: priority),
                              method: :put %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      Description:
      <p class="well"><%= @issue.description %></p>
    </div>
  </div>
  <div id="issue-actions">
    <div>
      <% if @issue.project.users.include?(current_user) %>
        <% if @issue.status == Status::ACTIVE %>
          <%= link_to 'Confirm issue', issue_path(@issue, set_status: Status::TO_BE_FIXED), class: 'btn btn-success', method: :put %>
        <% end %>
        <%= link_to 'Edit issue', edit_issue_path(@issue), class: 'btn btn-primary' %>
        <% if @issue.closed? %>
          <span> or </span>
          <%= link_to 'Reopen issue', issue_path(@issue, set_status: Status::ACTIVE), class: 'btn btn-primary', method: :put %>
        <% else %>
          <span> or close as </span>
          <%= link_to 'Fixed', issue_path(@issue, set_status: Status::FIXED), class: 'btn btn-success', method: :put %>
          <%= link_to 'By design', issue_path(@issue, set_status: Status::BY_DESIGN), class: 'btn btn-warning', method: :put %>
          <%= link_to 'Won\'t fix', issue_path(@issue, set_status: Status::WONT_FIX), class: 'btn btn-danger', method: :put %>
        <% end %>
      <% elsif @issue.user == current_user || @issue.project.users.include?(current_user) %>
        <% if @issue.closed? %>
          <%= link_to 'Reopen issue', issue_path(@issue, set_status: Status::ACTIVE), class: 'btn btn-primary', method: :put %>
        <% else %>
          <%= link_to 'Edit issue', edit_issue_path(@issue), class: 'btn btn-primary' %>
          <%= link_to 'Close issue', issue_path(@issue, set_status: Status::CLOSED), class: 'btn btn-danger', method: :put %>
        <% end %>
      <% end %>
    </div>
    <div>
      <% if !current_user.nil? && current_user.admin? %>
        <span>as admin </span>
        <%= link_to 'Remove issue', issue_path(@issue), class: 'btn btn-danger', method: :delete %>
      <% end %>
    </div>
    <%= link_to '← to project', @issue.project, class: 'btn' %>
  </div>
  <section class="comments">
    <div class="comments-header">
      Comments <%= content_tag :span, "(#{@issue.comments.count})", class: 'count' %>
    </div>
    <% if @issue.comments.any? %>
      <% @issue.comments.each do |comment| %>
        <div class="comment">
          <div class="header">
            <%= gravatar_for comment.user, size: 36 %>
            <%= link_to comment.user.name, comment.user %>
            <span class="timestamp"><%= comment.created_at %></span>
          </div>
          <div class="body">
            <%= simple_format h comment.message %>
          </div>
        </div>
      <% end %>
    <% end %>
    <% if signed_in? %>
      <%= render 'shared/comment_form' %>
    <% end %>
  </section>
</div>
<% if @issue.project.users.include? current_user %>
  <!-- assign issue modal -->
  <div class="modal" id="assign-issue-modal" style="display: none;">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">×</button>
      <h3>Assign this issue</h3>
    </div>
    <div class="modal-body">
      <%= form_tag assign_path, method: :put do %>
        <ul>
          <%= hidden_field_tag :id, @issue.id %>
          <% @issue.project.users.each do |user| %>
            <li><%= radio_button_tag 'user_id', user.id, user == @issue.assignee %>
            <%= gravatar_for user, size: 32 %>
            <%= label_tag "user_id_#{user.id}", user.name %></li>
          <% end %>
        </ul>
        <%= submit_tag 'Assign', class: 'btn btn-primary btn-large' %>
      <% end %>
    </div>
    <div class="modal-footer">
      <%= link_to 'Assign to nobody', assign_path(id: @issue.id, user_id: 0), method: :put, class: 'btn' %>
      <a href="#" class="btn" onclick="$('#assign-issue-modal').modal('hide')">Close</a>
    </div>
  </div>
<% end %>