config/routes.rb
Rbtrack::Application.routes.draw do
  root to: 'static_pages#home'
  resources :users
  resources :projects, only: [:new, :create, :show, :index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :issues, except: :index
  resources :comments, only: [:create]
  match '/assign', to: 'issues#assign', via: :put
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/invite', to: 'TeamMemberships#invite', via: :post
  match '/accept_invitation', to: 'TeamMemberships#accept_invitation', via: :put
  match '/reject_invitation', to: 'TeamMemberships#reject_invitation', via: :put
  match '/search', to: 'search#search'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean         default(FALSE)
#

class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :team_memberships, conditions: { invitation_accepted: true }
  has_many :projects, through: :team_memberships
  has_many :opened_issues, class_name: 'Issue'
  has_many :assigned_issues, class_name: 'Issue', foreign_key: 'assignee_id'
  has_many :comments

  attr_accessible :email, :name, :password_digest, :password, :password_confirmation
  has_secure_password

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  before_save -> user { user.email.downcase! }
  before_save :create_remember_token

  def active_reported_issues
    opened_issues.find_all { |issue| !issue.closed? }
  end
  def closed_reported_issues
    opened_issues.find_all { |issue| issue.closed? }
  end
  def invitations
    TeamMembership.find_all_by_user_id(id).find_all { |tm| !tm.invitation_accepted? }
  end

private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :not_signed_in_user, only: [:new, :create]
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  def new
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = 'Welcome to the rbTrack!'
      redirect_to @user
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end
  def index
    @users = User.paginate(page: params[:page])
  end
  def edit
  end
  def update
    if @user.update_attributes(params[:user])
      flash[:success] = 'Profile updated'
      sign_in @user
      redirect_to @user
    else
      render :edit
    end
  end
  def destroy
    user = User.find(params[:id])
    if current_user?(user)
      redirect_to root_path
    else
      user.destroy
      flash[:success] = "User #{user.name} with email address #{user.email} have been deleted."
      redirect_to users_path
    end
  end

private
  def not_signed_in_user
    redirect_to root_path unless !signed_in?
  end
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar', style: "width: #{size}px; height: #{size}px;")
  end
end

app/views/users/_fields.html.erb
<%= form.label :name %>
<%= form.text_field :name %>
<%= form.label :email %>
<%= form.text_field :email %>
<%= form.label :password %>
<%= form.password_field :password %>
<%= form.label :password_confirmation, 'Confirm password' %>
<%= form.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to 'delete', user, method: :delete, confirm: 'Are you sure?' %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit profile') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |form| %>
      <%= render 'shared/error_messages', object: form.object %>
      <%= render 'fields', form: form %>
      <%= form.submit 'Save changes', class: 'btn btn-large btn-primary' %>
    <% end %>
    <%= gravatar_for @user %>
    <%= link_to 'Change', 'http://gravatar.com/emails', target: '_blank' %>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for @user do |form| %>
      <%= render 'shared/error_messages', object: form.object %>
      <%= render 'fields', form: form %>
      <%= form.submit 'Create account', class: 'btn btn-large btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <div class="tabbable" id="user-projects">
      <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#projects">Projects <%= content_tag :span, "(#{@user.projects.count})", class: 'count' %></a></li>
        <% if current_user?(@user) && @user.invitations.any? %>
          <li><a data-toggle="tab" href="#invitations">Invitations <%= content_tag :span, "(#{@user.invitations.count})", class: 'count' %></a></li>
        <% end %>
      </ul>
      <div class="tab-content">
        <div id="projects" class="tab-pane active">
          <ul class="list">
            <% @user.projects.each do |project| %>
              <li>
                <%= link_to project.name, project %>
                <% if current_user?(@user) && @user == project.owner %>
                  <%= link_to 'Delete', project, method: :delete, class: 'btn btn-danger btn-mini', confirm: 'Are you sure? This action cannot be undone.' %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <% if current_user?(@user) && @user.invitations.any? %>
          <div id="invitations" class="tab-pane">
            <ul class="list">
              <% @user.invitations.each do |invitation| %>
                <li>
                  <%= link_to invitation.project.name, invitation.project, class: 'invitation-project-link' %>
                  <%= link_to 'Accept', accept_invitation_path(id: invitation.id), method: :put, class: 'btn btn-success invitation-action-link' %>
                  <%= link_to 'Reject', reject_invitation_path(id: invitation.id), method: :put, class: 'btn btn-danger invitation-action-link' %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
    <% if current_user? @user %>
      <span class='new-project'><%= link_to 'Create new project', new_project_path, class:'btn btn-primary new-project' %></span>
    <% end %>
  </aside>
  <div class="span8">
    <div>
      <%= if @user.assigned_issues.any?
            render 'shared/issues_list', project_id: nil, new_issue_button: false,
                 issues_lists: [ { issues: @user.assigned_issues, header: 'Assigned issues' } ]
          end %>
    </div>
    <br />
    <div>
      <%= render 'shared/issues_list', project_id: nil, new_issue_button: true,
                 issues_lists: [ { issues: @user.active_reported_issues, header: 'Active reported issues' },
                                 { issues: @user.closed_reported_issues, header: 'Closed reported issues' } ] %>
    </div>
  </div>
</div>