config/routes.rb
Rbtrack::Application.routes.draw do
  root to: 'static_pages#home'
  resources :users
  resources :projects, only: [:new, :create, :show, :index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :issues, except: :index
  resources :comments, only: [:create]
  match '/assign', to: 'issues#assign', via: :put
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/invite', to: 'TeamMemberships#invite', via: :post
  match '/accept_invitation', to: 'TeamMemberships#accept_invitation', via: :put
  match '/reject_invitation', to: 'TeamMemberships#reject_invitation', via: :put
  match '/search', to: 'search#search'

end

app/views/shared/_comment_form.html.erb
<div class="new-comment-form">
  <%= form_for @comment do |form| %>
    <%= render 'shared/error_messages', object: form.object %>
    <%= hidden_field_tag 'comment[issue_id]', @issue.id %>
    <%= form.text_area :message, rows: 3 %>
    <%= form.submit 'Comment on this issue', class: 'btn btn-large btn-primary' %>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error-explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, 'error') %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li>* <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_issue_priority_badge.html.erb
<% if tooltip %>
  <span class="label-badge <%= label_priority_class_from priority %>"><a href="#" title="<%= Priority.to_string priority %>"><i class="<%= icon_priority_class_from priority %>"></i></a></span>
<% else %>
  <span class="label-badge <%= label_priority_class_from priority %>"><i class="<%= icon_priority_class_from priority %>"></i></span>
<% end %>

app/views/shared/_issue_status_badge.html.erb
<% if tooltip %>
  <span class="label-badge <%= label_status_class_from status %>"><a href="#" title="<%= Status::to_string status %>"><i class="<%= icon_status_class_from status %>"></i></a></span>
<% else %>
  <span class="label-badge <%= label_status_class_from status %>"><i class="<%= icon_status_class_from status %>"></i></span>
<% end %>

app/views/shared/_issues_list.html.erb
<section class="issues-list">
  <div class="tabbable">
    <ul class="nav nav-tabs">
      <% issues_lists.each_with_index do |info, i| %>
        <li class="<%= i == 0 ? 'active' : '' %>">
          <a data-toggle="tab" href="#<%= issues_id_from info[:header] %>"><%= "#{info[:header]} (#{info[:issues].count})" %></a>
        </li>
      <% end %>
      <!-- TODO refactor this, span should not be inside ul -->
      <% if new_issue_button && (current_user?(@user) || !project_id.nil?) %>
        <span class='new-issue'><%= link_to 'Report an issue', new_issue_path(project: project_id), class:'btn btn-primary' %></span>
      <% end %>
    </ul>
    <div class="tab-content">
      <% issues_lists.each_with_index do |info, i| %>
        <div id="<%= issues_id_from info[:header] %>" class="tab-pane<%= i == 0 ? ' active' : '' %>">
          <ul class="list">
            <% info[:issues].each do |issue| %>
              <li><span class="id">#<%= issue.id %></span>
                <%= render 'shared/issue_status_badge', status: issue.status, tooltip: true %>
                <%= render 'shared/issue_priority_badge', priority: issue.priority, tooltip: true %>
                <% if project_id.nil? %>
                  (<%= link_to issue.project.name, issue.project %>)
                <% end %>
                <% max_length = 60 %>
                <%= link_to truncate(issue.subject, length: max_length), issue, title: issue.subject.length > max_length ? issue.subject : '' %>
                <% unless project_id.nil? %>
                  (<%= issue.assignee.nil? ? 'nobody' : (link_to issue.assignee.name, issue.assignee) %>)
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/shared/_search_form.html.erb
<% query_id = "query#{'-inline' if options[:inline]}" %>
<% search_id = "search#{'-inline' if options[:inline]}" %>
<%= form_tag search_path, method: :get, class: "#{options[:inline] ? 'navbar-search form-search-inline' : 'form-search'}" do %>
  <%= text_field_tag :query, params[:query], id: query_id, class: "search-query #{'span11' unless options[:inline]}" %>
  <%= submit_tag 'Search', id: search_id, name: nil, class: "btn #{options[:inline] ? 'btn-mini btn-inverse' : 'btn-large'}",
    onclick: '$.Watermark.HideAll()' %>
  <script type="text/javascript">
    $('form input#<%= query_id %>').Watermark('Search for projects or issues')
  </script>
<% end %>