config/routes.rb
Rbtrack::Application.routes.draw do
  root to: 'static_pages#home'
  resources :users
  resources :projects, only: [:new, :create, :show, :index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :issues, except: :index
  resources :comments, only: [:create]
  match '/assign', to: 'issues#assign', via: :put
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/invite', to: 'TeamMemberships#invite', via: :post
  match '/accept_invitation', to: 'TeamMemberships#accept_invitation', via: :put
  match '/reject_invitation', to: 'TeamMemberships#reject_invitation', via: :put
  match '/search', to: 'search#search'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Dmitry Polyanitsa
  </small>
  <nav>
    <ul>
      <li>Contact me: <%= mail_to 'coffeecup.winner@gmail.com' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'rbTrack', root_path, id: 'logo' %>
      <nav>
        <ul class="nav pull-left">
          <li class="divider-vertical"></li>
          <li><%= render 'shared/search_form', options: { inline: true } %></li>
        </ul>
        <ul class="nav pull-right">
          <li><%= link_to 'Home', root_path %></li>
          <% if signed_in? %>
            <li><%= link_to 'Projects', projects_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', signout_path, method: 'delete' %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Sign in', signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" />
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>